name: 'AI inference Test'

on: workflow_dispatch

jobs:
  lint-and-inference:
    runs-on: ubuntu-latest
    permissions:
      models: read
    steps:

      # --- (Optional) Checkout if you need prompt-file from repo ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Second AI inference step using prompt file ---
      - name: Run AI Inference with Prompt File
        id: inference_file
        uses: actions/ai-inference@v1
        with:
          prompt-file: '.github/prompts/documentation/mud-system.md'
          max-tokens: 1000

      - name: Print AI Output from prompt file
        run: |
          echo "Prompt-file response:"
          echo "${{ steps.inference_file.outputs.response }}"
